llm_config:
  model: HuggingFaceTB/SmolLM2-360M-Instruct
  temperature: 0.5
img_config:
  model: segmind/tiny-sd
  width: 512
  height: 512
  hardware: cpu
  negative_prompt: low quality, deformed, blurry, watermark, text
embedding_model: sentence-transformers/all-MiniLM-L6-v2
system_prompt: "You are a helpful AI assistant. Your name is Aeon.\nContext: {context}"