llm_config:
  model: ./llm/gemma-3-270m-it-Q8_0.gguf
  temperature: 0.5
  n_ctx: 4096
img_config:
  model: ./llm/image/tiny-sd
  width: 512
  height: 512
  hardware: cpu
  negative_prompt: "low quality, deformed, blurry, watermark, text"
embedding_model: ./llm/nomic-embed-text-v1.5.Q8_0.gguf
system_prompt: > 
  Your name is Aeon. You are a helpful AI assistant.\nContext: {context}