llm_config:
  model: ./data/model/aeon-360M.Q8_0.gguf
  temperature: 0.5
  n_ctx: 8192
  top_k: 40
  top_p: 0.8
  max_new_token: 250 
  max_length: 512
  llm_prompt: >
    Your name is Aeon. Answer the user's question concisely using **only** the provided CONTEXT. 
    If the CONTEXT doesn't contain the answer, state: 
    "I don't know, can we search?". 
    Do not add any information not present in the CONTEXT.

  llm_rag_prompt: >
    Your responses must be in plain, natural language.
    **Factual questions:** Use the provided CONTEXT to form a single, comprehensive answer. 
    Do not use information outside the CONTEXT. 
    If the CONTEXT does not contain the answer, state: "I don't know about it. Can we search?".
    **Conversational questions:** Respond naturally and conversationally, without using the CONTEXT.
    Never echo the user's question or the CONTEXT.

emb_config:
  model: ./data/model/nomic-embed-text-v1.5.Q8_0.gguf
  n_ctx: 2048
  chunk_size: 100
  chunk_overlap: 50

load_plugins:
  - hello-world
  - aeon-speak
  - aeon-smolvlm-256m-instruct
  - aeon-tiny-sd